version: "3.3"

services:

  # PRODUCTION
  phenotips-prod:
    container_name: lpac-pt-PROD
    image: gene42/gene42-phenotips-core:latest
    restart: "no"
    #ports:
    #    - "127.0.0.1:8080:8080"
    #    - "127.0.0.1:8009:8009"
    expose:
      - "8080"
      - "8009"
    volumes:
      - lpac-pt-PROD_local-storage:/var/lib/phenotips/
    cap_drop:
      - SYS_ADMIN

  # STAGE
  phenotips-stage:
    container_name: lpac-pt-STAGE
    image: gene42/gene42-phenotips-core:latest
    restart: "no"
    #ports:
    #    - "127.0.0.1:8081:8080"
    #    - "127.0.0.1:8010:8009"
    expose:
      - "8080"
      - "8009"
    volumes:
      - lpac-pt-STAGE_local-storage:/var/lib/phenotips/
    cap_drop:
      - SYS_ADMIN

  # NGINX Proxy
  proxy:
    container_name: lpac-proxy
    image: library/nginx:1.13-alpine
    ports:
      - "9001:80"
      - "9002:443"


volumes:
  lpac-pt-PROD_local-storage:
  lpac-pt-STAGE_local-storage:
